#camera parameters file paths

cam1: /home/rama/bpc_ws/bpc/ipd/camera_cam1.json
cam2: /home/rama/bpc_ws/bpc/ipd/camera_cam2.json
cam3: /home/rama/bpc_ws/bpc/ipd/camera_cam3.json
photoneo: /home/rama/bpc_ws/bpc/ipd/camera_photoneo.json

# metadata path
meta_data_folder: /home/rama/bpc_ws/bpc/test_pipeline/metadata


# MaskRCNN
maskrcnn_model_path: "/home/rama/bpc_ws/bpc/maskRCNN/output/ipd_val/model_epoch_235.pth"
maskrcnn_output_path: "/home/rama/bpc_ws/bpc/maskRCNN/results"
maskrcnn_confidence_threshold: 0.8
maskrcnn_category_txt_path: "/home/rama/bpc_ws/bpc/maskRCNN/categories.txt"
maskrcnn_visualization_and_save: true

# Build 3D PCL
save_pcl: false

# ROI Extraction
roi_extraction_output_path: "/home/rama/bpc_ws/bpc/roi_extraction/output"
save_rois: true

## Register

register_reference_models_path: "/home/rama/bpc_ws/bpc/ipd/models"
register_output_path: "/home/rama/bpc_ws/bpc/pointcloud_registration/registration_results"
registration_visualization_and_save: true

# Parallel processing settings
parallel_processing:
  max_workers: null  # Auto-detect, or set specific number
  use_gpu: true
  gpu_batch_size: 64
  memory_efficient: true

# Reference dataset CSV
ref_csv_path: /home/rama/bpc_ws/bpc/utilities/filtered_dataset.csv

