# Request

# List of object IDs to look for in the scene.
uint64[] object_ids

# Scene images.
sensor_msgs/CameraInfo rgb_info
sensor_msgs/Image rgb
sensor_msgs/CameraInfo depth_info
sensor_msgs/Image depth
sensor_msgs/CameraInfo polarized_info
sensor_msgs/Image polarized

---

# Response
PoseEstimate[] pose_estimates