name: style
on:
  pull_request:
  push:
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: ['jazzy']
    container:
      image: ros:${{ matrix.distro }}-ros-base
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - name: black
      run: sudo apt update && sudo apt install ros-${{ matrix.distro }}-ament-black -y && /ros_entrypoint.sh ament_black ./